

export enum SupportCategoriesEnum {
    MedicalAssistance = "Медична допомога",
    HousingConditions = "Житлові умови",
    FoodAndGroceries = "Харчування та продукти",
    Education = "Освіта та навчання",
    EmergencyAssistance = "Екстренна допомога",
    ChildSupport = "Допомога дітям",
    FamilySupport = "Підтримка сімей",
    ElderlySupport = "Допомога людям похилого віку",
    DisabilitySupport = "Допомога особам з інвалідністю",
    PsychologicalSupport = "Психологічна підтримка",
    HomelessSupport = "Допомога бездомним",
    MaterialAssistance = "Матеріальна допомога",
    FinancialSupport = "Фінансова підтримка",
    ClothingAndFootwear = "Одяг та взуття",
    HygieneAndPersonalCare = "Гігієна та особиста догляд",
    TransportationCosts = "Транспортні витрати",
    EnvironmentalSupport = "Допомога в екологічних питаннях",
    AnimalSupport = "Підтримка тварин та захист їх прав",
    SocialAdaptation = "Соціальна адаптація",
    LegalAssistance = "Юридична допомога та правова підтримка",
    ApplianceRepair = "Відновлення побутової техніки",
    MobilityAndAccessibility = "Мобільність та доступність",
    CultureAndLeisure = "Культура та дозвілля",
    CreativityAndSkillsDevelopment = "Розвиток креативності та навичок",
    HealthyLifestyle = "Здоровий спосіб життя",
    MigrantAndRefugeeSupport = "Підтримка мігрантів та біженців",
    JobSearchAssistance = "Допомога в пошуку роботи",
    MedicalEquipmentAndDevices = "Медичне обладнання та пристрої",
    MedicalTransport = "Медичний транспорт",
    RelocationAssistance = "Допомога в переселенні",
    WarVeteransSupport = "Підтримка учасників війни та ветеранів",
    FuneralOrganizationAssistance = "Допомога в організації похорону",
    AnimalMedicalAssistance = "Медична допомога тваринам",
    UtilityBillsAssistance = "Допомога в оплаті комунальних послуг",
    HousingRepairAndMaintenance = "Ремонт та утримання житла",
    WinterPreparationAssistance = "Допомога в підготовці до зими",
    LocalCommunitySupport = "Підтримка місцевих громад",
    WasteDisposalAssistance = "Допомога в утилізації відходів",
    ArtistsAndArtisansSupport = "Підтримка художників та митців",
    ProfessionalRehabilitation = "Професійна реабілітація"
}